
/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "GUI.h"
#include "MainTask.h"
//#include "FreeRTOS.h"
//#include "task.h"
#include "rtthread.h"
#include "rthw.h"
#include "DIALOG.h"
#include "ADC.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_GRAPH_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_0     (GUI_ID_USER + 0x02)
#define ID_TEXT_0     (GUI_ID_USER + 0x03)
#define ID_SLIDER_0     (GUI_ID_USER + 0x04)
#define ID_TEXT_1     (GUI_ID_USER + 0x05)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "RT-Thread_STemWin_Test", ID_FRAMEWIN_0, 0, 0, 320, 240, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 85, 0, 230, 220, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 10, 15, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 15, 60, 50, 30, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 30, 80, 20, 80, 9, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 10, 170, 60, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
WM_HWIN text_Item_0;
WM_HWIN text_Item_1;
GRAPH_DATA_Handle Graphdata;

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static int clicked = 0;
static int catch_time =0;

extern rt_event_t adc_startEvent_Handle;

static void _cbDialog(WM_MESSAGE* pMsg) {
    int NCode;
    int Id;
    char str[5];
    // USER START (Optionally insert additional variables)
    // USER END
    WM_HWIN button_Item_0;
    WM_HWIN slider_Item_0;
    WM_HWIN hItem;
    GRAPH_SCALE_Handle hScaleV;
    GRAPH_SCALE_Handle hScaleH;
    button_Item_0 = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    text_Item_0 = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    text_Item_1 = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    slider_Item_0 = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        BUTTON_SetText(button_Item_0, "start");
        BUTTON_SetFont(button_Item_0, &GUI_Font24_ASCII);
        TEXT_SetFont(text_Item_0, &GUI_Font16B_ASCII);
        TEXT_SetTextAlign(text_Item_0, TEXT_CF_HCENTER);
        TEXT_SetText(text_Item_1, "19:00");
        TEXT_SetFont(text_Item_1, &GUI_Font24B_ASCII);
        TEXT_SetTextAlign(text_Item_1, TEXT_CF_HCENTER);
        SLIDER_SetDefaultBarColor(slider_Item_0);
        SLIDER_SetRange(slider_Item_0,0,10);
        SLIDER_SetNumTicks(slider_Item_0,5);
        SLIDER_SetValue(slider_Item_0,5);
        catch_time = 5;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
        GRAPH_SetColor(hItem, GUI_BLACK, GRAPH_CI_BK);
        GRAPH_SetColor(hItem, GUI_WHITE, GRAPH_CI_GRID);
        GRAPH_SetBorder(hItem, 20, 5, 10, 20);
        GRAPH_SetGridDistX(hItem, 10);
        GRAPH_SetGridDistY(hItem, 10);
        GRAPH_SetLineStyleH(hItem, GUI_LS_DOT);
        GRAPH_SetLineStyleV(hItem, GUI_LS_DOT);
        GRAPH_SetGridVis(hItem, 1);
        /* 创建刻度对象 */
        hScaleV = GRAPH_SCALE_Create(10, GUI_TA_HCENTER | GUI_TA_LEFT,
            GRAPH_SCALE_CF_VERTICAL, 50);
        GRAPH_SCALE_SetTextColor(hScaleV, GUI_BLUE);
        GRAPH_AttachScale(hItem, hScaleV);
        GRAPH_SCALE_SetFactor(hScaleV, (double)5 / 150);
        hScaleH = GRAPH_SCALE_Create(205, GUI_TA_HCENTER | GUI_TA_LEFT,
            GRAPH_SCALE_CF_HORIZONTAL, 50);
        GRAPH_SCALE_SetTextColor(hScaleH, GUI_GREEN);
        GRAPH_AttachScale(hItem, hScaleH);
        GRAPH_SCALE_SetFactor(hScaleH, 1);
        /* 创建数据对象 */
        Graphdata = GRAPH_DATA_YT_Create(GUI_RED, 600, 0, 0);
        GRAPH_AttachData(hItem, Graphdata);
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_BUTTON_0: // Notifications sent by 'Button'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                clicked = 1 - clicked;
                if (clicked)
                {
                    BUTTON_SetText(button_Item_0, "stop");
					rt_event_send(adc_startEvent_Handle,ADC_START_EVENT);
                }
                else
                {
                    BUTTON_SetText(button_Item_0, "start");
					rt_event_send(adc_startEvent_Handle,ADC_STOP_EVENT);
                }
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        case ID_SLIDER_0: // Notifications sent by 'Slider'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
								SLIDER_SetValue(slider_Item_0,10-catch_time);
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
        
                catch_time = (10 - SLIDER_GetValue(slider_Item_0));
				if(!catch_time)
					catch_time = 1;
                //sprintf(str,"%d", 10 * catch_time);
								rt_sprintf(str,"%d",10 * catch_time);
                TEXT_SetText(text_Item_0, str);
							
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        }
        break;
        // USER START (Optionally insert additional code for further Ids)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateRT-Thread_STemWin_Test
*/
WM_HWIN Create_RT_Thread_STemWin_Test(void);
WM_HWIN Create_RT_Thread_STemWin_Test(void) {
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}


// USER START (Optionally insert additional public code)
// USER END
extern rt_mq_t time_mq_Handle;
extern rt_mailbox_t adc_mb_Handle;

void MainTask(void)
{
	int i=0;
	rt_err_t uwRet=RT_NULL;
	rt_uint16_t *temp;
//    time_t t;
//    time_t timer;
    char str[6];
//    struct tm* tcolock;
//    GUI_Init();
    Create_RT_Thread_STemWin_Test();
    //srand((unsigned)time(&t));
    while (1)
    {
		uwRet=rt_mq_recv(time_mq_Handle,str,sizeof(str),0);
		if(uwRet==RT_EOK)
		{
			TEXT_SetText(text_Item_1, str);
		}
//        timer = time(NULL);
//        tcolock = localtime(&timer);
//        strftime(str, 12, "%H:%M", tcolock);
//        TEXT_SetText(text_Item_1, str);
		
      //  if (clicked)
        {
            //temp = rand() % 150;
			rt_enter_critical();
			if(rt_mb_recv(adc_mb_Handle,(rt_uint32_t *)&temp,0)==RT_EOK)
			{
				for(i=0;i<10;i++)
				GRAPH_DATA_YT_AddValue(Graphdata, (rt_uint16_t)((double)((*(rt_uint16_t*)(temp+i)*3.3*30)/4096)));
			}
			rt_exit_critical();
        }
		
        GUI_Delay(10*catch_time);
    }
}

/*************************** End of file ****************************/
